### ISSUE TITLE
정적 팩토리 메소드 vs 생성자

### ISSUE THREAD

**Issue by great-park** [hellokitty-coding-club/LGTM-Backend#7]
> 정적 팩토리 메소드를 적용해본 코드인데, 저는 Service에서 직접 생성자로 member를 생성하는 것보다 member의 팩토리 메소드를 호출하는 것이 좀 더 좋다고 생각했습니다! 
> - 메소드 이름으로 "commonUserData로 부터 Member를 생성한다"는 것을 표현
> - 요구사항 변경으로 Member 생성에 대한 변경 or Member 생성 시 특정 작업 처리가 추가될 때, 팩토리 메소드에서 1번만 수정하면 해결 가능
> 
> 이 부분은 조윤호 팀원과 함께 고민하고 있어서 좀 더 이야기를 나눠보겠습니다!

_Originally posted by @great-park in https://github.com/hellokitty-coding-club/LGTM-Backend/pull/5#discussion_r1260638458_
            

pr comment 읽어보시고 의견 남겨주세요.

**Comment by ray-yhc** [comment]
저도 정적 팩토리 메소드를 적용해서 구현하는 것이 좋은 것 같습니다.
로직 내부에서 새로운 멤버 객체가 생성되어야 하는 경우는 회원가입 뿐이니 from 메소드를 통해 멤버객체의 생성 방법을 제한하는 것이 좋은 방법이라고 생각합니다.
특히, 요구조건의 변경으로 RequestBody 값이 변경되었을 때, Member 객체 내의 코드만 변경하면 되니 효율적이라고 생각합니다.

하지만, Effective Java의 Item.1 에서 나온 "정적 팩토리 메소드"의 기존 취지는
- 기본 생성자를 이용한 객체 생성을 막고, 정적 팩토리 메소드만을 사용해서 객체를 생성하도록 함
- 의도하지 않은 방식의 객체 생성을 방지
였는데, Member 객체는 @Entity 어노테이션으로 인해 AllArgsConstructor 사용이 불가피합니다.
그래서 기존 정적 팩토리 메소드의 사용 취지에서 조금은 벗어나는 것 같아 아쉬운 것 같네요 ㅜㅜ 엔티티라서 어쩔 수 없는 것 같습니다!
